### ISSUE TITLE
Faucet throwing 500s

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-blockchain-api#278]
As reported first in https://github.com/blockstack/stacks-wallet/issues/259, the faucet endpoint appears to be throwing 500s consistently, for the wallet and faucet page on blockstack.org:

<img width="1564" alt="Screen Shot 2020-10-07 at 15 14 28" src="https://user-images.githubusercontent.com/28991/95335604-e6d5c380-08af-11eb-8c22-5d49ac2fc20d.png">

**Comment by friedger** [comment]
This happens if there is more than one faucet tx in one block....

**Comment by agraebe** [comment]
@zone117x - is there an issue on the node repo for this? I'm assuming we need to fix this outside of this repo

**Comment by zone117x** [comment]
Full response:
```json
{
  "error": "Error: Response 400: Bad Request fetching http://stacks-node-miner.prod-krypton.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"ConflictingNonceInMempool\",\"txid\":\"48734b92a0c815a24f2c4665cc0d17913ac54f949d6eb960a60eeaa6144b7e1a\"}",
  "stack": "Error: Response 400: Bad Request fetching http://stacks-node-miner.prod-krypton.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"ConflictingNonceInMempool\",\"txid\":\"48734b92a0c815a24f2c4665cc0d17913ac54f949d6eb960a60eeaa6144b7e1a\"}\n    at StacksCoreRpcClient.fetchText (/app/lib/core-rpc/client.js:73:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async StacksCoreRpcClient.fetchJson (/app/lib/core-rpc/client.js:52:30)\n    at async StacksCoreRpcClient.sendTransaction (/app/lib/core-rpc/client.js:108:24)\n    at async /app/lib/api/routes/faucets.js:130:42\n    at async run (/app/node_modules/p-queue/dist/index.js:159:29)",
  "errorTag": "d0cd0d60-acc6-471d-99e8-94cda0d40c6f"
}
```

```json
{
  "error": "transaction rejected",
  "reason": "ConflictingNonceInMempool",
  "txid": "48734b92a0c815a24f2c4665cc0d17913ac54f949d6eb960a60eeaa6144b7e1a"
}
```

The faucet is directly submitting to the master node now, and is also doing nonce incrementation. Something with the master-node mempool seems broken.
