### ISSUE TITLE
[TESTNET BUG] A lot of "Error processing core node block message msg.matured_miner_rewards is not iterable"

### ISSUE THREAD

**Issue by jun0tpyrc** [blockstack/stacks-blockchain-api#349]
## Describe the bug

A lot of "Error processing core node block message msg.matured_miner_rewards is not iterable"

## Expected behavior

no stdout with error level 

## Environment

`docker run -p 3999:3999 -d --name blockstack blockstack/stacks-blockchain-api-standalone` 
at the time of pulling , should be https://hub.docker.com/layers/blockstack/stacks-blockchain-api-standalone/latest/images/sha256-e86b09d62818cdf920468b6421f54f19f563139787819386e867484e8b00268e?context=explore

## Additional context

in docker logs , a lot of similar lines with logs of "level"="error"
```

==> stacks-api.log <==
{"canonical":true,"block_hash":"0x64ab90ac4aa7d19580176dcf3ecd2f3616754dfb010972ec5cf45d72b4a76754","index_block_hash":"0x9bf5ea8cbfe60025c0aea41a6b3c2f35d2d83b38354a64570b99b224c890a0b3","parent_index_block_hash":"0x0d787bc3970f528b788fa9332d765d2c9c2e866c3bdcd3865af84255476926c2","parent_block_hash":"0x5d284da52f9bd96e1edb05b2b168f06153ef087b49d41b84fbd5c659f66e52fa","parent_microblock":"0x0000000000000000000000000000000000000000000000000000000000000000","block_height":1179,"burn_block_time":1606294719,"burn_block_hash":"0x194f8519028808e59514d7ed3811719a875031b3e6f16d0b3914f83610c7d1b7","burn_block_height":1581,"miner_txid":"0xdc7ea396c20865546fe08ccd4a1f937f14fd2b991275c4cabdbf4eb1874c6eb7","level":"verbose","message":"Received block 0x64ab90ac4aa7d19580176dcf3ecd2f3616754dfb010972ec5cf45d72b4a76754 (1179) from node","timestamp":"2020-11-25T09:01:20.690Z"}
{"level":"error","message":"Error processing core node block message msg.matured_miner_rewards is not iterable","stack":"TypeError: msg.matured_miner_rewards is not iterable\n    at handleClientMessage (/home/stacky/stacks-blockchain-api/lib/event-stream/event-server.js:86:35)\n    at /home/stacky/stacks-blockchain-api/lib/event-stream/event-server.js:262:28\n    at run (/home/stacky/stacks-blockchain-api/node_modules/p-queue/dist/index.js:153:104)\n    at PQueue._tryToStartAnother (/home/stacky/stacks-blockchain-api/node_modules/p-queue/dist/index.js:101:38)\n    at /home/stacky/stacks-blockchain-api/node_modules/p-queue/dist/index.js:167:18\n    at new Promise (<anonymous>)\n    at PQueue.add (/home/stacky/stacks-blockchain-api/node_modules/p-queue/dist/index.js:148:16)\n    at Object.handleBlockMessage (/home/stacky/stacks-blockchain-api/lib/event-stream/event-server.js:262:18)\n    at /home/stacky/stacks-blockchain-api/lib/event-stream/event-server.js:312:34\n    at wrappedMiddleware (/home/stacky/stacks-blockchain-api/node_modules/@awaitjs/express/index.js:112:13)\n    at Layer.handle [as handle_request] (/home/stacky/stacks-blockchain-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/stacky/stacks-blockchain-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/stacky/stacks-blockchain-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/stacky/stacks-blockchain-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/stacky/stacks-blockchain-api/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/home/stacky/stacks-blockchain-api/node_modules/express/lib/router/index.js:335:12)","timestamp":"2020-11-25T09:01:20.690Z"}

==> stacks-node.log <==
INFO [1606294880.652860] [src/net/relay.rs:997] [ThreadId(6)] Processing newly received blocks: 2

==> stacks-api.log <==
{"canonical":true,"block_hash":"0xc603ad5055f137c5ddbe819cacf9ccb0852312849f5237afbbae9fb3854ef113","index_block_hash":"0x0c877ec83f68d6678b24d99dfc8dbfdafce6298b5feec3316aa6f67c1a485dfb","parent_index_block_hash":"0x9bf5ea8cbfe60025c0aea41a6b3c2f35d2d83b38354a64570b99b224c890a0b3","parent_block_hash":"0x64ab90ac4aa7d19580176dcf3ecd2f3616754dfb010972ec5cf45d72b4a76754","parent_microblock":"0x0000000000000000000000000000000000000000000000000000000000000000","block_height":1180,"burn_block_time":1606294839,"burn_block_hash":"0x4891bcf9e89dc719035a224a3be09c45105a55dc7c8053b1944ae8ff7674bff2","burn_block_height":1582,"miner_txid":"0x7fb3a8dfe80efe6f7f667bdbcc94046de134eb25b734f79b38c762288036c780","level":"verbose","message":"Received block 0xc603ad5055f137c5ddbe819cacf9ccb0852312849f5237afbbae9fb3854ef113 (1180) from node","timestamp":"2020-11-25T09:01:20.725Z"}
{"level":"error","message":"Error processing core node block message msg.matured_miner_rewards is not iterable","stack":"TypeError: msg.matured_miner_rewards is not iterable\n    at handleClientMessage (/home/stacky/stacks-blockchain-api/lib/event-stream/event-server.js:86:35)\n    at /home/stacky/stacks-blockchain-api/lib/event-stream/event-server.js:262:28\n    at run (/home/stacky/stacks-blockchain-api/node_modules/p-queue/dist/index.js:153:104)\n    at PQueue._tryToStartAnother (/home/stacky/stacks-blockchain-api/node_modules/p-queue/dist/index.js:101:38)\n    at /home/stacky/stacks-blockchain-api/node_modules/p-queue/dist/index.js:167:18\n    at new Promise (<anonymous>)\n    at PQueue.add (/home/stacky/stacks-blockchain-api/node_modules/p-queue/dist/index.js:148:16)\n    at Object.handleBlockMessage (/home/stacky/stacks-blockchain-api/lib/event-stream/event-server.js:262:18)\n    at /home/stacky/stacks-blockchain-api/lib/event-stream/event-server.js:312:34\n    at wrappedMiddleware (/home/stacky/stacks-blockchain-api/node_modules/@awaitjs/express/index.js:112:13)\n    at Layer.handle [as handle_request] (/home/stacky/stacks-blockchain-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/stacky/stacks-blockchain-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/stacky/stacks-blockchain-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/stacky/stacks-blockchain-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/stacky/stacks-blockchain-api/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/home/stacky/stacks-blockchain-api/node_modules/express/lib/router/index.js:335:12)","timestamp":"2020-11-25T09:01:20.726Z"}
```

and this endpoint keeps long time at 
```
ubuntu@ip-172-31-61-173:~$ curl 0:3999/extended/v1/block?limit=1 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    45  100    45    0     0   9000      0 --:--:-- --:--:-- --:--:--  9000
{
  "limit": 1,
  "offset": 0,
  "total": 0,
  "results": []
}
``` 
not sure if related too

**Comment by jun0tpyrc** [comment]
nice for the promptly fix, may we also trigger the build of docker image blockstack/stacks-blockchain-api-standalone for latest version? Thanks~
