### ISSUE TITLE
Occasionally writing to postgres halting at some height (e.g. mainnet 1351)

### ISSUE THREAD

**Issue by jun0tpyrc** [blockstack/stacks-blockchain-api#418]
we have 2 machines running this  , both stopping at the same height 
running 
```
blockstack/stacks-blockchain:2.0.1
blockstack/stacks-blockchain-api:0.41.1
postgres:12.2
```

still stuck on
```
blockstack/stacks-blockchain:2.0.2
blockstack/stacks-blockchain-api:0.47.1
postgres:12.2
```

we also encountered this before

**Comment by zone117x** [comment]
@jun0tpyrc there's a few historical bugs that could cause this, but should be addressed in the latest version you're running (0.47.1). 
Do you have logs from the API?

**Comment by jun0tpyrc** [comment]
`stacks-node xenon` seems can't get us connected to the testnet now, even with `blockstack/stacks-blockchain:latest@sha256:be83fa58ecfa066b031e1f091f49d3773fe28b25e06e08ac8adc6ee596a286e3` image
```
ERRO [1612417286.071017] [src/burnchains/bitcoin/network.rs:208] [main] Failed to connect to peer 35.245.241.185:18333: connection to peer could not be (re-)established
```

**Comment by diwakergupta** [comment]
@jun0tpyrc are you using a local bitcoind? If not, that would be the fastest way to unblock yourself. 

@CharlieC3 `35.245.241.185` is `bitcoind.xenon.blockstack.org`. We used to run a restricted testnet bitcoind just for follower nodes (similar to the mainnet setup). Has that changed with the most recent reset? If so, we'll also need to update code in `stacks-blockchain` so that `stacks-node xenon` picks up the right defaults.

**Comment by CharlieC3** [comment]
@diwakergupta It seems the testnet's bitcoind was not externally reachable due to a port conflict. I fixed the conflict and confirmed I can now reach the the bitcoin node at `bitcoind.xenon.blockstack.org:18333`. The rpc port however is restricted and not available.

**Comment by jun0tpyrc** [comment]
for the mainnet stucking at certain level
```
blockstack/stacks-blockchain:2.0.2
blockstack/stacks-blockchain-api:0.47.1
```

this log from `stacks-blockchain-api` might help explain 

```
Error processing core node mempool message
error: column "nonce" of relation "mempool_txs" does not exist
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 130,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '147',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1034',
  routine: 'checkInsertTargets'
}
```

going to try newer artifacts without version tag...

**Comment by jun0tpyrc** [comment]
putting 
```
blockstack/stacks-blockchain:2.0.3
blockstack/stacks-blockchain-api:0.47.2
```

we got errors like 
```
{"message":"Received burn block message hash 0x00000000000000000004c83adcb47c97b251d3417f9b77d899469be859f44eb9, height: 668485","level":"verbose","timestamp":"2021-02-05T08:51:45.261Z"}
{"message":"Received burn block rewards for 3 recipients","level":"verbose","timestamp":"2021-02-05T08:51:45.261Z"}
Error processing core node burn block message
TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at /app/lib/event-stream/event-server.js:25:28
    at Array.map (<anonymous>)
    at handleBurnBlockMessage (/app/lib/event-stream/event-server.js:18:52)
    at /app/lib/event-stream/event-server.js:291:28
    at run (/app/node_modules/p-queue/dist/index.js:153:104)
    at PQueue._tryToStartAnother (/app/node_modules/p-queue/dist/index.js:101:38)
    at /app/node_modules/p-queue/dist/index.js:167:18
    at new Promise (<anonymous>)
    at PQueue.add (/app/node_modules/p-queue/dist/index.js:148:16)
    at Object.handleBurnBlock (/app/lib/event-stream/event-server.js:291:18)
    at /app/lib/event-stream/event-server.js:345:34
    at wrappedMiddleware (/app/node_modules/@awaitjs/express/index.js:112:13)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
```
