### ISSUE TITLE
API BNS crash after processing V1 data

### ISSUE THREAD

**Issue by CharlieC3** [blockstack/stacks-blockchain-api#514]
**Describe the bug**
The API built from the `bns` branch crashes when starting, seemingly right after Stacks V1 data is processed. This error started occurring after the `subdomain_zonefiles.txt` file was corrected in the GCP bucket and in the exported-data archive. Prior to that update this branch would start without crashing.

**To Reproduce**
Start the API from the `bns` branch, set the `BNS_IMPORT_DIR` ENV var to a directory containing an extracted exported-data dir from [this link](https://storage.googleapis.com/blockstack-v1-migration-data/export-data.tar.gz).

**Expected behavior**
API starts and does not crash.

**Console log**
```
> @blockstack/stacks-blockchain-api@1.0.0 start /app
> node ./lib/index.js

dotenv-flow: "PG_HOST" is already defined in `process.env` and will not be overwritten
dotenv-flow: "PG_PORT" is already defined in `process.env` and will not be overwritten
dotenv-flow: "PG_USER" is already defined in `process.env` and will not be overwritten
dotenv-flow: "PG_PASSWORD" is already defined in `process.env` and will not be overwritten
dotenv-flow: "PG_DATABASE" is already defined in `process.env` and will not be overwritten
dotenv-flow: "STACKS_CORE_EVENT_PORT" is already defined in `process.env` and will not be overwritten
dotenv-flow: "STACKS_CORE_EVENT_HOST" is already defined in `process.env` and will not be overwritten
dotenv-flow: "STACKS_BLOCKCHAIN_API_PORT" is already defined in `process.env` and will not be overwritten
dotenv-flow: "STACKS_BLOCKCHAIN_API_HOST" is already defined in `process.env` and will not be overwritten
dotenv-flow: "STACKS_CORE_RPC_HOST" is already defined in `process.env` and will not be overwritten
dotenv-flow: "STACKS_CORE_RPC_PORT" is already defined in `process.env` and will not be overwritten
dotenv-flow: "STACKS_CHAIN_ID" is already defined in `process.env` and will not be overwritten
dotenv-flow: "BTC_RPC_HOST" is already defined in `process.env` and will not be overwritten
dotenv-flow: "BTC_RPC_PORT" is already defined in `process.env` and will not be overwritten
dotenv-flow: "BTC_RPC_USER" is already defined in `process.env` and will not be overwritten
dotenv-flow: "BTC_RPC_PW" is already defined in `process.env` and will not be overwritten
dotenv-flow: "BTC_FAUCET_PK" is already defined in `process.env` and will not be overwritten
dotenv-flow: "GIT_TAG" is already defined in `process.env` and will not be overwritten
{"message":"Stacks 1.0 BNS data import started","level":"info","timestamp":"2021-03-19T14:15:17.713Z"}
{"message":"chainprocessor: importer starting","level":"info","timestamp":"2021-03-19T14:15:18.004Z"}
{"message":"chainprocessor: namespaces rows added: 12","level":"info","timestamp":"2021-03-19T14:15:18.078Z"}
{"message":"chainprocessor: missing zonefile for 7.id hash 6608abae9e288738505472c618b441cc629942fe","level":"warn","timestamp":"2021-03-19T14:15:18.201Z"}
{"message":"chainprocessor: missing zonefile for attache.id hash 64f931a4597a14c632d4689be87039652a0d904e","level":"warn","timestamp":"2021-03-19T14:15:19.078Z"}
{"message":"chainprocessor: missing zonefile for bitcoinbook.id hash ","level":"warn","timestamp":"2021-03-19T14:15:19.398Z"}
{"message":"chainprocessor: missing zonefile for block.id hash 10c4fe3e076a8b65f8639908166fe1bb1cd34c89","level":"warn","timestamp":"2021-03-19T14:15:19.574Z"}
{"message":"chainprocessor: missing zonefile for blockstack.id hash ","level":"warn","timestamp":"2021-03-19T14:15:19.629Z"}
{"message":"chainprocessor: missing zonefile for jayden.id hash 7ce15b387cbd1991def962a927278fd1b595df04","level":"warn","timestamp":"2021-03-19T14:15:23.580Z"}
{"message":"chainprocessor: missing zonefile for johnson.id hash 0323b65ba4510802c0c9ba894b7833cf7cc4d7d6","level":"warn","timestamp":"2021-03-19T14:15:23.811Z"}
{"message":"chainprocessor: missing zonefile for pjoter.miner hash 5d631221e9ca1f1c396fa51d8420177c32e58356","level":"warn","timestamp":"2021-03-19T14:15:26.497Z"}
{"message":"chainprocessor: missing zonefile for pravica.miner hash 6f70ba7f0a4daf027afc9d5ff341f664c4f802dc","level":"warn","timestamp":"2021-03-19T14:15:26.655Z"}
{"message":"chainprocessor: missing zonefile for vslice_dev_crux.id hash 2f0db44a91e4592eb1c988ed0ea238fd8afbfb6e","level":"warn","timestamp":"2021-03-19T14:15:29.008Z"}
{"message":"chainprocessor: missing zonefile for wagecan_dev_crux.id hash 1f0c7459f0745e0ce537434851fef79c40e4669c","level":"warn","timestamp":"2021-03-19T14:15:29.022Z"}
{"message":"chainprocessor: missing zonefile for waves_dev_crux.id hash ad9aa8dae47f6f9b956b690d6e3e28fd7e94ef43","level":"warn","timestamp":"2021-03-19T14:15:29.092Z"}
{"message":"chainprocessor: names rows added: 1643","level":"info","timestamp":"2021-03-19T14:15:29.743Z"}
{"message":"chainprocessor: importer done","level":"info","timestamp":"2021-03-19T14:15:32.052Z"}
{"level":"error","message":"app failed to start: Error: Unordered entries between subdomains.csv and subdomain_zonefiles.txt! Expected hash 03692c329056c9ff7754901f840952807cfcd966 got 01f821b3721beb971076c14a91f65b922f62f672 Unordered entries between subdomains.csv and subdomain_zonefiles.txt! Expected hash 03692c329056c9ff7754901f840952807cfcd966 got 01f821b3721beb971076c14a91f65b922f62f672","stack":"Error: Unordered entries between subdomains.csv and subdomain_zonefiles.txt! Expected hash 03692c329056c9ff7754901f840952807cfcd966 got 01f821b3721beb971076c14a91f65b922f62f672\n    at readSubdomains (/app/lib/import-v1/index.js:269:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Object.asyncBatchIterate (/app/lib/helpers.js:366:26)\n    at async Object.importV1 (/app/lib/import-v1/index.js:303:22)\n    at async init (/app/lib/index.js:74:9)","timestamp":"2021-03-19T14:15:32.111Z"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @blockstack/stacks-blockchain-api@1.0.0 start: `node ./lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @blockstack/stacks-blockchain-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-19T14_15_32_130Z-debug.log```

The API crashes after this last log.

**Comment by CharlieC3** [comment]
Fixed after correcting the `subdomains.csv` and `sha256` files in GCP.
