### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by boohyung** [blockstack/stacks-blockchain-api#548]
Hi, I want to execute postgres and stacks-blockchain-api(API Server) v0.55.3 "manually" because I already have manual stacks-node(built from https://github.com/blockstack/stacks-blockchain repo). But I encountered the error. What should I do for resolving problem?

[what I did]
```bash
npm install
npm run dev
```

[error]
```bash
npm run dev

> @blockstack/stacks-blockchain-api@1.0.0 dev /home/bhlee/stacks-blockchain-api
> cross-env NODE_ENV=development STACKS_BLOCKCHAIN_API_DB=pg ts-node src/index.ts

/home/bhlee/stacks-blockchain-api/src/helpers.ts:278
        const gitTag = (child_process_1.execSync('git tag --points-at HEAD', { encoding: 'utf8' }) ?? '').trim();
                                                                                                    ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module.m._compile (/home/bhlee/stacks-blockchain-api/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/bhlee/stacks-blockchain-api/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/bhlee/stacks-blockchain-api/src/index.ts:1:1)
```

**Comment by zone117x** [comment]
Looks like you are probably running an older version of NodeJS which doesn't support the `??` operator. Update to the current active LTS version (v14.x).

**Comment by boohyung** [comment]
Thanks!! But PostgreSQL is not set. I can't find the PostgreSQL setting guide. Can you tell me where I can find it?

**Comment by zone117x** [comment]
See the following env vars for postgres: 
https://github.com/blockstack/stacks-blockchain-api/blob/e625623ae5daa78096dbd6e510ad4240bf8e87f8/.env#L1-L5

**Comment by boohyung** [comment]
Thank you for your suport @zone117x
