### ISSUE TITLE
Investigate `unique_microblock_hash unique constraint` bug reported by integrator

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#695]
An integrator is reporting an error while syncing testnet with latest API develop branch. It's a critical issue that halts syncing their testnet:
```
2021-08-09_18:26:42.05827 {"length":288,"name":"error","severity":"ERROR","code":"23505","detail":"Key (microblock_hash)=(\\x34de6eeb40ac5da340ce43ace789bda5d8a1036b17d596e7d1575f23e4a493a7) already exists.","schema":"public","table":"microblocks","constraint":"unique_microblock_hash","file":"nbtinsert.c","line":"570","routine":"_bt_check_unique","level":"error","message":"Error processing core node microblock message duplicate key value violates unique constraint \"unique_microblock_hash\"","stack":"error: duplicate key value violates unique constraint \"unique_microblock_hash\"\n    at Parser.parseErrorMessage (/stacks-blockchain-api/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/stacks-blockchain-api/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/stacks-blockchain-api/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/stacks-blockchain-api/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (events.js:375:28)\n    at addChunk (internal/streams/readable.js:290:12)\n    at readableAddChunk (internal/streams/readable.js:265:9)\n    at Socket.Readable.push (internal/streams/readable.js:204:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)","timestamp":"2021-08-09T18:26:42.058Z"}
```

> it looks like after the node fully syncs to the tip, it starts getting those event_dispatcher errors again

Deployment details:
> no changes to dockerfile other than pointing the dockerfile to pull develop branch for stacks api and v2.0.11.2.0 for node
https://github.com/blockstack/stacks-blockchain-api/blob/develop/stx-rosetta.Dockerfile#L1-L2

I have their event-replay-log file to investigate. In the meantime, we should test re-syncing a testnet deployment from scratch to see if there's some issue that is somehow bypassed when the event-replay feature is used. cc @CharlieC3

**Comment by zone117x** [comment]
This appears to be caused when the `stacks-node` is accidentally configured to broadcast duplicate events to the API via the usage of both the `STACKS_EVENT_OBSERVER` env var and the `event_observer` toml config.

In the API develop branch, this error surfaces when duplicate `/new_block` events containing microblocks are received -- which can take hours to surface due to syncing times. 

While the API is incidentally capable of handling some types of duplicate events due to robust re-org detection and restoration code, it is not a goal of the API and should be considered undefined behavior. I'm not opposed to implementing explicit "duplicate event payload" detection into the API as a last minute safeguard, however, I think this should be handled first in the `stacks-blockchain` repo. The `stacks-node` process should detect when both `STACKS_EVENT_OBSERVER` env var and `event_observer` toml are specified for the same host and immediately panic with a configuration error.
