### ISSUE TITLE
Flaky BNS tests

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#723]
The CI bns tests are flaky and failing around half the time.

Here's the output for one of the failures:
```
  ● BNS integration tests › name-revoke contract call

    : Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Error:

      514 |   });
      515 |
    > 516 |   test('name-revoke contract call', async () => {
          |   ^
      517 |     //name revoke
      518 |     const txOptions: SignedContractCallOptions = {
      519 |       contractAddress: deployedTo,

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests-bns/bns-integration-tests.ts:516:3)
      at Object.<anonymous> (tests-bns/bns-integration-tests.ts:56:1)
```

**Comment by agraebe** [comment]
@zone117x could this be taken on by Tintash? Could we add a priority and move to the backlog if so?

**Comment by asimm241** [comment]
@MHassanTariq is working on it!

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/stacks-blockchain-api/pull/788
