### ISSUE TITLE
[Rosetta][Bug] /block on testnet block index 6859 returns error

### ISSUE THREAD

**Issue by shermanxiong** [blockstack/stacks-blockchain-api#732]
## Request on Rosetta API /block
```
{
  "network_identifier": {
    "blockchain": "stacks",
    "network": "testnet"
  },
  "block_identifier": {
    "index": 6859,
    "hash": "0x0a6073da8c936a3005702a3c8d3280eba2759cbece7757fc71406d7e47be8366"
  }
}
```

## Error Response
```
{
  "error": "Error: Invalid pox address hash mode: 196",
  "stack": "Error: Invalid pox address hash mode: 196\n    at hashModeToBtcAddressVersion (/stacks-blockchain-api/node_modules/@stacks/stacking/src/utils.ts:67:13)\n    at Object.poxAddressToBtcAddress (/stacks-blockchain-api/node_modules/@stacks/stacking/src/utils.ts:137:29)\n    at parseDelegateStxArgs (/stacks-blockchain-api/src/rosetta-helpers.ts:643:25)\n    at parseStackingContractCall (/stacks-blockchain-api/src/rosetta-helpers.ts:557:14)\n    at makeCallContractOperation (/stacks-blockchain-api/src/rosetta-helpers.ts:418:9)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Object.getOperations (/stacks-blockchain-api/src/rosetta-helpers.ts:110:23)\n    at getRosettaBlockTransactionsFromDataStore (/stacks-blockchain-api/src/api/controllers/db-controller.ts:507:24)\n    at Object.getRosettaBlockFromDataStore (/stacks-blockchain-api/src/api/controllers/db-controller.ts:324:16)\n    at /stacks-blockchain-api/src/api/routes/rosetta/block.ts:31:19\n    at wrappedMiddleware (/stacks-blockchain-api/node_modules/@awaitjs/express/index.js:62:7)",
  "errorTag": "e16e3c12-3d61-4d16-b4ed-336c29b5e4d4"
}

```

**Comment by asimm241** [comment]
I'm unable to reproduce this issue on my end.

The request: 
```
curl -X POST \
  https://stacks-node-api.testnet.stacks.co/rosetta/v1/block \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 23d6439b-0f05-99e2-4e04-e536ddf85c2d' \
  -d '{
  "network_identifier": {
    "blockchain": "stacks",
    "network": "testnet"
  },
  "block_identifier": {
    "index": 6859,
    "hash": "0x0a6073da8c936a3005702a3c8d3280eba2759cbece7757fc71406d7e47be8366"
  }
}'
```
The Response: 
```
{
    "block": {
        "block_identifier": {
            "index": 6859,
            "hash": "0x0a6073da8c936a3005702a3c8d3280eba2759cbece7757fc71406d7e47be8366"
        },
        "parent_block_identifier": {
            "index": 6858,
            "hash": "0x2e2a428e22afc0a0fd7c05cc11e656b5466f55da837b71bbd9a3c34e438f5bae"
        },
        "timestamp": 1630071246000,
        "transactions": [
            {
                "transaction_identifier": {
                    "hash": "0xc9d8abaa1a0b646f536a850578c4a54f595fb95886d1cf0083422761c8ef1a36"
                },
                "operations": [
                    {
                        "operation_identifier": {
                            "index": 0
                        },
                        "type": "fee",
                        "status": "success",
                        "account": {
                            "address": "ST1X6M947Z7E58CNE0H8YJVJTVKS9VW0PHEG3NHN3"
                        },
                        "amount": {
                            "value": "-366",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 1
                        },
                        "type": "contract_call",
                        "status": "abort_by_post_condition",
                        "account": {
                            "address": "ST1X6M947Z7E58CNE0H8YJVJTVKS9VW0PHEG3NHN3"
                        },
                        "metadata": {
                            "contract_call_function_name": "rawr",
                            "contract_call_function_args": "0x0000000701000000000000000000000000000004d200ffffffffffffffffffffffffffffff16020000000c68656c6c6f2c20776f726c640d000000096865792d61736369690e000000086865792d75746638051a7a6a2487f9dc5432ae0451e96e5adcf29df0168b03"
                        }
                    }
                ]
            },
            {
                "transaction_identifier": {
                    "hash": "0x41706da445ac744570a95548472add8485e8c4d59bfc105474dca2ef22d6a4e7"
                },
                "operations": [
                    {
                        "operation_identifier": {
                            "index": 0
                        },
                        "type": "fee",
                        "status": "success",
                        "account": {
                            "address": "SN1ZGXNRC63P7E64TZR9MAJ837W0NYC483Q847CPC"
                        },
                        "amount": {
                            "value": "-590",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 1
                        },
                        "type": "delegate_stx",
                        "status": "success",
                        "account": {
                            "address": "SN1ZGXNRC63P7E64TZR9MAJ837W0NYC483Q847CPC"
                        },
                        "metadata": {
                            "amount_ustx": "23000000",
                            "delegate_to": "ST1XAY5AEZH5BJYYSY7N8S0DN4A6WDWT1194FWR8G",
                            "until_burn_height": "none",
                            "result": "true"
                        }
                    }
                ]
            },
            {
                "transaction_identifier": {
                    "hash": "0x39af8bdcadab4605f89c0904dde76d1a4c45fb16b28b1b3572fbd7cfd8c78f68"
                },
                "operations": [
                    {
                        "operation_identifier": {
                            "index": 0
                        },
                        "type": "fee",
                        "status": "success",
                        "account": {
                            "address": "ST3YFTC2T8AWRBN8FNYP0B8E42F954SYSN3MCCNW5"
                        },
                        "amount": {
                            "value": "-180",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 1
                        },
                        "type": "token_transfer",
                        "status": "success",
                        "account": {
                            "address": "ST3YFTC2T8AWRBN8FNYP0B8E42F954SYSN3MCCNW5"
                        },
                        "amount": {
                            "value": "-40000000",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        },
                        "coin_change": {
                            "coin_action": "coin_spent",
                            "coin_identifier": {
                                "identifier": "0x39af8bdcadab4605f89c0904dde76d1a4c45fb16b28b1b3572fbd7cfd8c78f68:1"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 2
                        },
                        "related_operations": [
                            {
                                "index": 1
                            }
                        ],
                        "type": "token_transfer",
                        "status": "success",
                        "account": {
                            "address": "ST1BC527GYN5AHTGFSFSNGGAV0PHJTE10NKE6PJ2M"
                        },
                        "amount": {
                            "value": "40000000",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        },
                        "coin_change": {
                            "coin_action": "coin_created",
                            "coin_identifier": {
                                "identifier": "0x39af8bdcadab4605f89c0904dde76d1a4c45fb16b28b1b3572fbd7cfd8c78f68:2"
                            }
                        }
                    }
                ]
            },
            {
                "transaction_identifier": {
                    "hash": "0x4b105979e231a9e3d76a25b5298290d160790608492e6e59f0d7fb16d1017978"
                },
                "operations": [
                    {
                        "operation_identifier": {
                            "index": 0
                        },
                        "type": "fee",
                        "status": "success",
                        "account": {
                            "address": "ST1X6M947Z7E58CNE0H8YJVJTVKS9VW0PHEG3NHN3"
                        },
                        "amount": {
                            "value": "-163",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 1
                        },
                        "type": "contract_call",
                        "status": "success",
                        "account": {
                            "address": "ST1X6M947Z7E58CNE0H8YJVJTVKS9VW0PHEG3NHN3"
                        },
                        "metadata": {
                            "contract_call_function_name": "faucet",
                            "contract_call_function_args": ""
                        }
                    }
                ]
            },
            {
                "transaction_identifier": {
                    "hash": "0xd3edd643b636b1ef0a294c2d6d67bd32678dbf0550dd5d669fe463d6bf3a7bb5"
                },
                "operations": [
                    {
                        "operation_identifier": {
                            "index": 0
                        },
                        "type": "fee",
                        "status": "success",
                        "account": {
                            "address": "ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2"
                        },
                        "amount": {
                            "value": "-180",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 1
                        },
                        "type": "token_transfer",
                        "status": "success",
                        "account": {
                            "address": "ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2"
                        },
                        "amount": {
                            "value": "-500000000",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        },
                        "coin_change": {
                            "coin_action": "coin_spent",
                            "coin_identifier": {
                                "identifier": "0xd3edd643b636b1ef0a294c2d6d67bd32678dbf0550dd5d669fe463d6bf3a7bb5:1"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 2
                        },
                        "related_operations": [
                            {
                                "index": 1
                            }
                        ],
                        "type": "token_transfer",
                        "status": "success",
                        "account": {
                            "address": "ST3YFTC2T8AWRBN8FNYP0B8E42F954SYSN3MCCNW5"
                        },
                        "amount": {
                            "value": "500000000",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        },
                        "coin_change": {
                            "coin_action": "coin_created",
                            "coin_identifier": {
                                "identifier": "0xd3edd643b636b1ef0a294c2d6d67bd32678dbf0550dd5d669fe463d6bf3a7bb5:2"
                            }
                        }
                    }
                ]
            },
            {
                "transaction_identifier": {
                    "hash": "0xee4e6b7a63d9eb61eac696ffeca1526f222231638252fcaf356b10e2b9cc3283"
                },
                "operations": [
                    {
                        "operation_identifier": {
                            "index": 0
                        },
                        "type": "fee",
                        "status": "success",
                        "account": {
                            "address": "ST1ABV23F0DXCEAFBYBHAX9T2NM51MC19Q4K6JDY9"
                        },
                        "amount": {
                            "value": "-291",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 1
                        },
                        "type": "contract_call",
                        "status": "success",
                        "account": {
                            "address": "ST1ABV23F0DXCEAFBYBHAX9T2NM51MC19Q4K6JDY9"
                        },
                        "metadata": {
                            "contract_call_function_name": "transfer",
                            "contract_call_function_args": "0x000000030100000000000000000000000000000005051a54bd886f037ac729ebf2e2aea742ad0a1a3029b9051ade95fba03e8172865a17b7dd14625d7f0f1d13d1"
                        }
                    }
                ]
            },
            {
                "transaction_identifier": {
                    "hash": "0x863a026204138bbe50bdea3eba8f240fcc831f77f90a7072e7c274277d19fee5"
                },
                "operations": [
                    {
                        "operation_identifier": {
                            "index": 0
                        },
                        "type": "fee",
                        "status": "success",
                        "account": {
                            "address": "ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2"
                        },
                        "amount": {
                            "value": "-180",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 1
                        },
                        "type": "token_transfer",
                        "status": "success",
                        "account": {
                            "address": "ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2"
                        },
                        "amount": {
                            "value": "-500000000",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        },
                        "coin_change": {
                            "coin_action": "coin_spent",
                            "coin_identifier": {
                                "identifier": "0x863a026204138bbe50bdea3eba8f240fcc831f77f90a7072e7c274277d19fee5:1"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 2
                        },
                        "related_operations": [
                            {
                                "index": 1
                            }
                        ],
                        "type": "token_transfer",
                        "status": "success",
                        "account": {
                            "address": "ST1BC527GYN5AHTGFSFSNGGAV0PHJTE10NKE6PJ2M"
                        },
                        "amount": {
                            "value": "500000000",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        },
                        "coin_change": {
                            "coin_action": "coin_created",
                            "coin_identifier": {
                                "identifier": "0x863a026204138bbe50bdea3eba8f240fcc831f77f90a7072e7c274277d19fee5:2"
                            }
                        }
                    }
                ]
            },
            {
                "transaction_identifier": {
                    "hash": "0x209c5cd854e7f0670b9b300dbd8ac83d96bf496176cc3551d4e4296539415927"
                },
                "operations": [
                    {
                        "operation_identifier": {
                            "index": 0
                        },
                        "type": "coinbase",
                        "status": "success",
                        "account": {
                            "address": "ST2X2FYCY01Y7YR2TGC2Y6661NFF3SMH0NGXPWTV5"
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 1
                        },
                        "status": "success",
                        "type": "miner_reward",
                        "account": {
                            "address": "ST2X2FYCY01Y7YR2TGC2Y6661NFF3SMH0NGXPWTV5"
                        },
                        "amount": {
                            "value": "0",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 2
                        },
                        "status": "success",
                        "type": "miner_reward",
                        "account": {
                            "address": "ST2X2FYCY01Y7YR2TGC2Y6661NFF3SMH0NGXPWTV5"
                        },
                        "amount": {
                            "value": "1000001177",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        }
                    }
                ]
            },
            {
                "transaction_identifier": {
                    "hash": "0x84b093a34714a4ed115437dd6940007d244bbad9e8d878e633b7ad52c6e898b1"
                },
                "operations": [
                    {
                        "operation_identifier": {
                            "index": 0
                        },
                        "type": "fee",
                        "status": "success",
                        "account": {
                            "address": "STCA7FJ72J7HW7KBHDV57BD676KQ1C5D2TA45AZP"
                        },
                        "amount": {
                            "value": "-698",
                            "currency": {
                                "decimals": 6,
                                "symbol": "STX"
                            }
                        }
                    },
                    {
                        "operation_identifier": {
                            "index": 1
                        },
                        "type": "contract_call",
                        "status": "success",
                        "account": {
                            "address": "STCA7FJ72J7HW7KBHDV57BD676KQ1C5D2TA45AZP"
                        },
                        "metadata": {
                            "contract_call_function_name": "job-create-one",
                            "contract_call_function_args": "0x000000010c0000000c09636f6d70616e7949640200000001310a637573746f6d657249640200000001310f637573746f6d6572526563656976650a01000000000000000000000000000000010e637573746f6d657257616c6c65740a051a461249e07f920bcf4d17fb6f2f7cf9fb1d7ab2af0b6973456e63727970746564030a6a6f6244657461696c7302000000c1c100000010696400a84a05000274797065000a000000696e7175697269657300026e756d626572000a00000048432d373935303534000273746172745f74696d65001e000000323032312d30382d30345431303a30303a30302e3030302b30373a303000027374617465001300000070656e64696e675f636f6d706c6574696f6e00086861735f6c6f67697374696373000002637265617465645f6174001e000000323032312d30372d32355431343a30363a30332e3932382b30373a30300000056a6f6249640200000001310c6f7468657244657461696c730200000003e480800570726963650200000001320a70726f766964657249640200000001310f70726f76696465725265636569766501000000000000000000000000000000010e70726f766964657257616c6c6574051ab4b882397baa55a90aa8ff596b27f2cae499a3d7"
                        }
                    }
                ]
            }
        ]
    }
}
```

cc: @zone117x

**Comment by shermanxiong** [comment]
im running `v0.64.2` and attempted a sync from scratch to try to see if it would resolve. it didnt work, still receiving same error

**Comment by zone117x** [comment]
I'm able to produce it on latest. It looks like many `delegate-stx` contract calls are providing a non-standard format for the `pox-addr`. In the case of this error, the tx is https://stacks-node-api.testnet.stacks.co/extended/v1/tx/0x41706da445ac744570a95548472add8485e8c4d59bfc105474dca2ef22d6a4e7

```json
{
"hex": "0x0a0c0000000209686173686279746573020000001433bca9edc296f59e1a933e32af18ee1891a2045d0776657273696f6e0200000001c4",
"repr": "(some (tuple (hashbytes 0x33bca9edc296f59e1a933e32af18ee1891a2045d) (version 0xc4)))",
"name": "pox-addr",
"type": "(optional (tuple (hashbytes (buff 20)) (version (buff 1))))"
}
```

The value `0xc4` (196) is causing `poxAddressToBtcAddress` to throw at https://github.com/blockstack/stacks-blockchain-api/blob/1914333f669e4ff8d4497e715cb703ca17d14fae/src/rosetta-helpers.ts#L643

The value `196` is bitcoin testnet P2SH address version rather than a Stacks address hash mode.

AFAIK the encoding for this specific `delegate-stx` arg is somewhat free-form, as the pool operator can choose how to interpret this address data. So I think in this case it probably makes sense to make leave the `pox_addr` field in delegate STX as the original hex encoded clarity value.
